[package]
name = "kimbo"
version = "0.1.6"
authors = ["Jamie Whiting"]
edition = "2021"
description = "check extensions"

[dependencies]
kimbo_state = { git = "https://github.com/JacquesRW/kimbo_state" }
fastrand = "1.8.0"

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.release]
panic = "abort"
lto = true
strip = true
debug = false
incremental = false

[profile.dev]
opt-level = 3